apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yb-cluster-create
spec:
  params:
    - name: tanzu-cluster-name
      type: string
    - name: tanzu-container-image
      type: string
  steps:
    - name: step-yb-setup
      image: $(params.tanzu-container-image)
      securityContext:
        privileged: true
        runAsUser: 0
      command: ["/bin/bash"]
      args: 
      - "/tmp/02-yugabyte-platform-install.sh"
      env:
      - name: TANZU_YB_SECRET
        valueFrom:
          secretKeyRef:
            name: yb-secret
            key: TANZU_YB_SECRET
      - name: TANZU_CLUSTER_NAME
        value: $(params.tanzu-cluster-name)