apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: yb-cluster-reset
spec:
  params:
    - name: tanzu-cluster-name
      type: string
    - name: tanzu-container-image
      type: string
  tasks:
    - name: yb-cluster-reset-task
      taskRef:
        name: yb-cluster-reset-task
      params:
        - name: tanzu-cluster-name
          value: $(params.tanzu-cluster-name)
        - name: tanzu-container-image
          value: $(params.tanzu-container-image)
