apiVersion: v1
kind: Secret
metadata:
  name: yugabyte-k8s-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJlWFZuWVdKNWRHVXJlV0p3WVhKMGJtVnlYM1JoYm5wMU9rcEpORXhPVTBkUVdGZzBUVVZIV1V4WlREUk9UbFJXTjA1UFVFZFVPVWRGVUZoRFVVOVVSVTgwV2pGTFZsVTRUakZIV2xGRk56TkZRek5DU0VKT09Vbz0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
